---
api:
  params:
    page: 1
    pagesize: 10
    order: asc
    sort: creation
    filter: "!56AvQjKHW2kPEINpNffehC8rTZ(UFXpKHgHhFU"
    site: stackoverflow
  use_cache: true
redis:
  decode_responses: yes
  cache_expire: 60
sof_handler:
  default_path: "./data"
  
...