---
api:
  
  params:
    page: 1
    page_size: 10
    order: desc
    sort: creation
    filter: "!-OzlL6z3TRuLDUz)e0rMDN*CjpMxEyd8v"
    site: stackoverflow
redis:
  host: localhost
  port: 6379
  db: 0
  decode_responses: yes
  cache_expire: 60
db:
  host: localhost
  port: 5432
  user: 
  password: 
  database: stackoverflow
...