---
api:
  params:
    page: 1
    pagesize: 10
    order: asc
    sort: creation
    filter: "!-OzlL6z3TRuLDUz)e0rMDN*CjpMxEyd8v"
    site: stackoverflow
redis:
  decode_responses: yes
  cache_expire: 60
...