---
api:
  params:
    page: 1
    pagesize: 10
    order: asc
    sort: creation
    filter: "!56AvQjU4bEYUoTdqt_zUKShh6TUK_ekUQULZ(-"
    site: stackoverflow
redis:
  decode_responses: yes
  cache_expire: 60
...